# Generated by Django 3.1.4 on 2021-02-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20210219_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='Email',
            new_name='email',
        ),
    ]
